#!/bin/bash
../build/src/girtobac /usr/share/gir-1.0/Atk-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/Atspi-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/cairo-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/DBus-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/DBusGLib-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/Dbusmenu-0.4.gir
../build/src/girtobac /usr/share/gir-1.0/fontconfig-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/freetype2-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GConf-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/Gda-5.0.gir
../build/src/girtobac /usr/share/gir-1.0/Gdk-3.0.gir
../build/src/girtobac /usr/share/gir-1.0/GdkPixbuf-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GdkPixdata-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GdkX11-3.0.gir
../build/src/girtobac /usr/share/gir-1.0/Gee-0.8.gir
../build/src/girtobac /usr/share/gir-1.0/Gio-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GIRepository-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GL-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/GLib-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GModule-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GObject-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/GooCanvas-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/Graphene-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/Gst-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/GstBase-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/GstCheck-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/GstController-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/GstNet-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/Gtk-3.0.gir
../build/src/girtobac /usr/share/gir-1.0/GtkSource-3.0.gir
../build/src/girtobac /usr/share/gir-1.0/GtkSpell-3.0.gir
../build/src/girtobac /usr/share/gir-1.0/HarfBuzz-0.0.gir
../build/src/girtobac /usr/share/gir-1.0/JavaScriptCore-4.0.gir
../build/src/girtobac /usr/share/gir-1.0/Json-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/libxml2-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/Pango-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/PangoCairo-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/PangoFc-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/PangoFT2-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/PangoOT-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/PangoXft-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/Poppler-0.18.gir
../build/src/girtobac /usr/share/gir-1.0/Soup-2.4.gir
../build/src/girtobac /usr/share/gir-1.0/SpiceClientGLib-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/SpiceClientGtk-3.0.gir
../build/src/girtobac /usr/share/gir-1.0/Vulkan-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/WebKit2-4.0.gir
../build/src/girtobac /usr/share/gir-1.0/WebKit2WebExtension-4.0.gir
../build/src/girtobac /usr/share/gir-1.0/win32-1.0.gir
../build/src/girtobac /usr/share/gir-1.0/xfixes-4.0.gir
../build/src/girtobac /usr/share/gir-1.0/xft-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/xlib-2.0.gir
../build/src/girtobac /usr/share/gir-1.0/xrandr-1.3.gir
